Added setter getter to change button imputs for PID tuner
EZ-Robotics/EZ-Template pull request #249
Opened 2024-12-20 22:02 UTC by nightwolf3140

## Summary:

Added getter setter functions to change PID tuner buttons. This allows the end user to more easily change the imputs without digging through the libraries.
## Motivation:

https://github.com/EZ-Robotics/EZ-Template/issues/244
### References (optional):

## Test Plan:

- [ ] Test original functionality of PID tuner still works
- [ ] Test with changing button imputs

2024-12-21 01:12 UTC, ssejrog requested changes
The changes look good so far, I've requested a couple changes. 

Along with these changes, can you also add:
- a function that gets each button
- functions to set/get the other 4 buttons used in the PID tuner

Thank you!

2024-12-21 01:12 UTC, ssejrog commented on include/EZ-Template/drive/drive.hpp
> +   */
```suggestion
  /**
   * Sets the buttons to change the PID tuner.
   *
   * \param decrease
   *        sets the button to lower PID tuner
   * \param increase 
   *        sets the button to increase PID tuner
   */
```

2024-12-21 01:12 UTC, ssejrog commented on src/EZ-Template/drive/pid_tuner.cpp
> +pros::controller_digital_e_t pid_tuner_decrease;
These should be created in `private` in `drive.hpp`

2025-01-02 02:20 UTC, nightwolf3140 commented
> The changes look good so far, I've requested a couple changes.
> 
> Along with these changes, can you also add:
> 
>     * a function that gets each button
> 
>     * functions to set/get the other 4 buttons used in the PID tuner
> 
> 
> Some of the changes are small, we don't currently have contributing guidelines so this is very helpful in figuring out what we need to include in that.
> 
> Thank you!

Added all four buttons.

2025-01-02 23:24 UTC, ssejrog commented
Confirmed this works with the following test:
```cpp
  chassis.pid_tuner_button_decrement_set(DIGITAL_A);
  chassis.pid_tuner_button_increment_set(DIGITAL_Y);
  chassis.pid_tuner_button_up_set(DIGITAL_DOWN);
  chassis.pid_tuner_button_down_set(DIGITAL_UP);
  chassis.pid_tuner_button_left_set(DIGITAL_RIGHT);
  chassis.pid_tuner_button_right_set(DIGITAL_LEFT);
  ```

2025-01-02 23:44 UTC, ssejrog approved these changes
Everything looks good now, ready to merge :D

2025-05-27 03:35 UTC, merged